name: mincloset
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Dùng một khoảng rộng hơn cho tương thích

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  uuid: ^4.4.0
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.1
  google_generative_ai: ^0.4.3
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  logger: ^2.4.0
  intl: ^0.19.0
  screenshot: ^3.0.0 
  path_provider: ^2.1.3
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2
  sqflite_common_ffi: ^2.3.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/materials/
    - assets/images/patterns/ 