name: mincloset
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Dùng một khoảng rộng hơn cho tương thích

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  image: ^4.2.0 
  image_picker: ^1.1.2
  uuid: ^4.4.0
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.1
  google_generative_ai: ^0.4.3
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  logger: ^2.4.0
  intl: ^0.20.2
  screenshot: ^3.0.0 
  path_provider: ^2.1.3
  share_plus: ^11.0.0
  equatable: ^2.0.5
  geolocator: ^14.0.2
  geocoding: ^4.0.0 
  fl_chart: ^1.0.0
  font_awesome_flutter: ^10.7.0
  pro_image_editor: ^10.1.1
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  sentry_flutter: ^9.1.0
  dotted_border: ^3.0.1
  fpdart: ^1.1.1
  material_symbols_icons: ^4.2815.1
  google_fonts: ^6.2.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  table_calendar: ^3.2.0
  collection: ^1.19.1
  onnxruntime: ^1.4.1
  ffi: ^2.1.4
  image_background_remover: ^1.0.0
  showcaseview: ^4.0.1
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.6
  connectivity_plus: ^6.1.4 
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  sentry_dart_plugin: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  rename: ^3.0.2
  sqflite_common_ffi: ^2.3.3
  flutter_lints: ^6.0.0
  geocoding_platform_interface: ^3.2.0 
  geolocator_platform_interface: ^4.2.6
  plugin_platform_interface: ^2.1.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - assets/images/badges/
    - assets/images/weather_backgrounds/
    - assets/images/materials/
    - assets/images/patterns/ 
    - assets/images/insights/

fonts:
    - family: BeVietnamPro
      fonts:
        - asset: fonts/BeVietnamPro-Regular.ttf
        - asset: fonts/BeVietnamPro-Italic.ttf
          style: italic
        - asset: fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: fonts/BeVietnamPro-Bold.ttf
          weight: 700

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: mincloset
  org: madebymin

flutter_launcher_icons:
  # Cài đặt cho Android
  android: "launcher_icon"
  
  # Cài đặt cho iOS
  ios: true
  
  # Đường dẫn tới file icon gốc bạn đã chuẩn bị ở Bước 1
  image_path: "assets/icon/icon.png"
  
  # Chỉ định phiên bản Android tối thiểu, thường là 21
  min_sdk_android: 21
  
  # Cài đặt cho Web
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
    
  # Cài đặt cho Windows
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # Kích thước icon cho file .ico

  # Cài đặt cho macOS
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

# Cấu hình cho flutter_native_splash
flutter_native_splash:
  # Màu nền của màn hình chờ. Bạn có thể dùng mã hex.
  color: "#1ABC9C"

  # Đường dẫn đến file ảnh bạn muốn hiển thị.
  image: assets/icon/icon640.png

  # Cấu hình cho Android 12+
  android_12:
    color: "#1ABC9C"
    image: assets/icon/icon640.png