// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnir4ae3N2RPLKyGNNftkBXPl8ub1SofM',
    appId: '1:35306730291:web:e5f7a4562f22b7c5a24446',
    messagingSenderId: '35306730291',
    projectId: 'mincloset-vn',
    authDomain: 'mincloset-vn.firebaseapp.com',
    storageBucket: 'mincloset-vn.firebasestorage.app',
    measurementId: 'G-QRBYBLWM1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByO-_mrA-6FBMcYIgoWQAZJRxmQfiEh6Y',
    appId: '1:35306730291:android:112b9d7b10967779a24446',
    messagingSenderId: '35306730291',
    projectId: 'mincloset-vn',
    storageBucket: 'mincloset-vn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU73igVCPi6ModHz_jo2ChTX5JU324ai0',
    appId: '1:35306730291:ios:568af1fec1c708d5a24446',
    messagingSenderId: '35306730291',
    projectId: 'mincloset-vn',
    storageBucket: 'mincloset-vn.firebasestorage.app',
    iosClientId: '35306730291-v9gn9frs2dsgbn8hrlbkp4i6e85023te.apps.googleusercontent.com',
    iosBundleId: 'com.example.mincloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU73igVCPi6ModHz_jo2ChTX5JU324ai0',
    appId: '1:35306730291:ios:568af1fec1c708d5a24446',
    messagingSenderId: '35306730291',
    projectId: 'mincloset-vn',
    storageBucket: 'mincloset-vn.firebasestorage.app',
    iosClientId: '35306730291-v9gn9frs2dsgbn8hrlbkp4i6e85023te.apps.googleusercontent.com',
    iosBundleId: 'com.example.mincloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnir4ae3N2RPLKyGNNftkBXPl8ub1SofM',
    appId: '1:35306730291:web:ddb387efc81864f4a24446',
    messagingSenderId: '35306730291',
    projectId: 'mincloset-vn',
    authDomain: 'mincloset-vn.firebaseapp.com',
    storageBucket: 'mincloset-vn.firebasestorage.app',
    measurementId: 'G-4L6XMWYB1E',
  );

}